language: php

cache:
    directories:
        - $HOME/.composer/cache/files

matrix:
    fast_finish: true
    include:
          # Test the latest stable release
        - php: 5.5
        - php: 5.6
        - php: 7.0
        - php: 7.1
        - php: 7.2

script:
    - composer inst
    - vendor/bin/phpcs .
#    - vendor/bin/phpstan anal -l 7 lib/
    - vendor/bin/phpunit